### ISSUE TITLE
CSV: Should have ability to fill width with a single column

### ISSUE THREAD

**Issue by dpeet** [GetTerminus/terminus-ui#1174]
I am using the CSV Component.  By default it looks like this
![image](https://user-images.githubusercontent.com/4729779/50234759-65343f00-0384-11e9-8b32-f62428e21fd8.png)

I want the Component to fill the available space like this
![image](https://user-images.githubusercontent.com/4729779/50234803-79783c00-0384-11e9-8e62-b7d3f00f2001.png)

I used the below code to create that effect
```scss
.c-csv-entry .c-csv-entry__row {
  display: block !important;
}

.c-csv-entry__input {
  width: 100%;
}

ts-csv-entry {
  display: block;
  width: 100%;
} 
```

---

- [ ] Add `@Input` to force full width
  - `singleColumnMode: boolean`
  - Default to `false`
