### ISSUE TITLE
Typography: Improve mixin to no longer output duplicate font-family styles

### ISSUE THREAD

**Issue by benjamincharity** [GetTerminus/terminus-ui#1555]
Currently the default font-family is added every time the `typography` mixin is called; even when the mixin is called in a way that requires a different font family.

### Reproduction

This code:
```
.test {
  @included typography(fixedwidth)
}
```

Creates this output:

```css
.test {
  font-family: Roboto, Helvetica Neue, Helvetica, Arial, sans-serif;
  font-family: Lucida Console, Monaco, DejaVu Sans Mono, monospace;
}
```

### Offending code

https://github.com/GetTerminus/terminus-ui/blob/release/terminus-ui/scss/helpers/_typography.scss#L112-L118

---

- [ ] Refactor so that only a single `font-family` declaration is output
